# Task - 6 (Numpy - Both for Basic and Adv User) of Data Science Internship with Innomatics Research Labs 
### Name= Achal Mate

### 1.Arrays

In [1]:
import numpy

def arrays(arr):
    return numpy.array(arr[::-1], float)

        
    # complete this function
    # use numpy.array

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### 2.Shape and Reshape

In [2]:
import numpy
arr = input().split(" ")
X = numpy.array(arr,int)
print(X.reshape(3, 3))


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 3.Transpose and Flatten



In [3]:
import numpy

N,M = map(int,input().split(" "))
array = numpy.array([input().split(" ") for i  in range(N)], int)
print (array.transpose())
print (array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


### 4.Concatenate

In [8]:
import numpy as np

n, m, p = map(int, input().split())   

source = " ".join(input() for _ in range(n))  
matrix1 = np.array(source.split(), int)
matrix1.shape = (n, p)

source = " ".join(input() for _ in range(m)) 
matrix2 = np.array(source.split(), int)    
matrix2.shape = (m, p)

print(np.concatenate((matrix1, matrix2), axis=0)) 

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### 5. Zeros and Ones



In [13]:
import numpy as np
shape = list(map(int, input().split()))
print(np.zeros(shape, int), np.ones(shape, int), sep='\n')

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


### 6.Eye and Identity

In [15]:
import numpy
numpy.set_printoptions(sign=' ')
N,M = map(int,input().split(" "))
print(numpy.eye(N, M))


2 2
[[ 1.  0.]
 [ 0.  1.]]


### 7.Array Mathematics

In [1]:
import numpy
N,M = map(int,input().split(" "))
A = numpy.array([input().split(" ") for i  in range(N)], int)
B = numpy.array([input().split(" ") for i  in range(N)], int)

print(numpy.add(A, B))         

print(numpy.subtract(A, B))  
print(numpy.multiply(A, B))               
print(A//B)      
print(numpy.mod(A,B))          
print(numpy.power(A,B))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


### 8. Floor, Ceil and Rint



In [2]:
import numpy
A = numpy.array(input().split(),float)
numpy.set_printoptions(sign=' ')
print(numpy.floor(A))  
print(numpy.ceil(A))
print(numpy.rint(A))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


### 9. Sum and Prod

In [3]:
import numpy
n,m = map(int,input().split())
ar = numpy.array([input().split() for i in range(n)], int)
print(numpy.prod((numpy.sum(ar,axis=0))))


2 2
1 2
3 4
24


### 10. Min and Max

In [4]:
import numpy
n,m = map(int,input().split())
ar = numpy.array([input().split() for i in range(n)], int)
print(numpy.max((numpy.min(ar,axis=1))))


4 2
2 5
3 7
1 3
4 0
3


### 11 Mean, Var, and Std



In [5]:
import numpy
n,m = map(int,input().split())
ar = numpy.array([input().split() for i in range(n)], int)
print(numpy.mean(ar, axis = 1))
print(numpy.var(ar, axis = 0))
print(numpy.around(numpy.std(ar),decimals=11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


### 12 Dot and Cross

In [6]:
import numpy

N= int(input())
A = numpy.array([input().split(" ") for i  in range(N)], int)
B = numpy.array([input().split(" ") for i  in range(N)], int)

print(numpy.dot(A,B))



2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


### 13.Inner and Outer



In [7]:
import numpy

A = numpy.array(input().split(" "), int)
B = numpy.array(input().split(" "), int)
print(numpy.inner(A, B))
print(numpy.outer(A, B))


0 1
2 3
3
[[0 0]
 [2 3]]


### 14.Polynomials



In [8]:
import numpy

C = list(map(float,input().split()))
X = int(input())
print(numpy.polyval(C,X))



1.1 2 3
0
3.0


### 15 Linear Algebra

In [9]:
import numpy

N= int(input())
A = numpy.array([input().split() for i in range(N)],float)
print(round(numpy.linalg.det(A),2))

2
1.1 1.1
1.1 1.1
0.0
